### ISSUE TITLE
DW Editor toolbar disappears with Snippeter

### ISSUE THREAD

**Issue by kdmoyers** [geco2/snippeter#5] opened 2018-07-13 19:51 UTC
I'm have same issue: DW Editor toolbar disappears with Snippeter plugin. Only Uninstalling the plugin replaces the toolbar.

Also, although Extension Manager claims to have a 2016-01-25 version, the version installed says it is 2014-08-20, and then again complains that a new version is available. Even manually downloading from Github, the plugin.info.txt file says it's 2014-08-20. Not sure what to believe.

Frustrating because this plugin sounds ideal to my needs, being much much simpler than Snippets.

I'm running DW Release 2018-04-22a "Greebo"

**Comment by geco2** [comment] 2018-07-14 20:12
Hi,

i'm using snippeter with Greebo as well... So that's at least tested ;-). Let me check what happens if i install DW Editor.
That date/version issue should be fixed with an update on the repositoy site ready to be tested in a  minute.

Thank you for get in contact! That help me to further maintain the plugin.

Regards,

Andi

**Comment by geco2** [comment] 2018-07-14 20:21
lol just realized that you refer to the DokuWiki Editor Toolbar... Sorry my fault. May i ask you for a list of your installed plugins?

**Comment by kdmoyers** [comment] 2018-07-16 11:19
Here they are: (I took this list from the Extension Manager screen)

ACL Manager by  Andreas GohrScreenshot of ACL Manager
Manage Page Access Control Lists

Active Directory Auth Plugin by  Andreas Gohr
Provides user authentication against a Microsoft Active Directory

Plain Auth Plugin by  Andreas Gohr
Provides user authentication against DokuWiki's local password storage

Configuration Manager by  Christopher SmithScreenshot of Configuration Manager
Manage Dokuwiki's Configuration Settings

Structured Data Plugin by  Andreas Gohr
Add and query structured data in your wiki

edittable plugin by  Andreas GohrScreenshot of edittable plugin
Provide a custom editor for tables

Extension Manager by  Michael HamannScreenshot of Extension Manager
Allows managing and installing plugins and templates

iframe plugin by  Christopher Smith
Allows external URLs to be loaded into an iframe in your DokuWiki page.

imgpaste plugin by  Andreas Gohr
Add images via cut'n'paste in Chrome

include plugin by  Michael Hamann, Gina Häussge, Christopher Smith, Michael Klier, Esther Brunner
Functions to include another page in a wiki page

Info Plugin by  Andreas Gohr
Displays information about various DokuWiki internals

orphanswanted plugin by  Doug Edmunds, Cyrille37, Federico Ariel Castagnini, Andy Webber, Matthias Schulte
Display Orphans, Wanteds and Valid link tables

Pagelist Plugin by  Matthias Schulte, Michael Hamann, Michael Klier, Gina Haeussge
Lists pages in a nice formatted way

Send anonymous data about your wiki to the DokuWiki developers

Publishing Plugin by  Jarrod Lowe, Andreas Gohr, Dominik Eckelmann
Integrate a publishing process into DokuWiki

Revert Manager by  Andreas GohrScreenshot of Revert Manager
Allows you to mass revert recent edits to remove Spam or vandalism

safefnrecode plugin by  Andreas Gohr
Changes existing page and foldernames for the change in the safe filename encoding

Searchindex Manager by  Andreas Gohr
Allows to rebuild the fulltext search index

sortablejs by  vaxquis
Allow sorting tables by columns

sqlite plugin by  Andreas Gohr
A helper plugin to easily access a SQLite database

styling plugin by  Andreas GohrScreenshot of styling plugin
Allows to edit style.ini replacements

SwiftMailer Plugin by  Andreas Gohr
Use SwiftMailer for sending mails from DokuWiki (uses SwiftMailer 3.3.3-php5)

Tag Plugin by  Michael Hamann, Gina Häussge, Christopher Smith, Michael Klier, Esther Brunner
tag wiki pages

ToDo by  Leo Eibler, Christian Marg, Markus Gschwendt
Create a checkbox based todo list with optional user assignment

DokuWiki Upgrade Plugin by  Andreas GohrScreenshot of DokuWiki Upgrade Plugin
Automatically upgrade your DokuWiki install to the most recent stable release

Update: New version 2018-06-07 is available.

User Manager by  Chris SmithScreenshot of User Manager
Manage DokuWiki user accounts

Wrap Plugin by  Anika Henke
Universal plugin which combines functionalities of many other plugins.

**Comment by geco2** [comment] 2018-07-16 21:14
Spend some time playing around with your list but unfortunately was not able to reproduce the issue.
Found a "bug" in the "Publishing Plugin" -> Naming issues
You should better move from the unsupportet "SwiftMailer" Plugin to "SMTP Plugin" cause the SwiftMailer does not support php7 and will not maintained any longer.

Do you see any error message in your webserver logfiles you can share? Software versions that allow me to "clone" your system state?

**Comment by kdmoyers** [comment] 2018-07-18 20:19
OK, here's what I have: 
* removed SwiftMailer (but no change to toolbar problem)
* tried latest Snippeter (version warning gone, but no change in toolbar problem)
* made disabled/enabled screen shots for you (below), with debug view turned on
* found the four lines added to the apache error log each time it happens (below)
Hope this helps!
-Kirby

> [Wed Jul 18 16:10:09.728254 2018] [:error] [pid 4220:tid 720] [client 192.168.10.138:53926] PHP Warning:  scandir(../../data/pages/snippets,../../data/pages/snippets): The system cannot find the file specified. (code: 2) in D:\\RAGs\\VertrigoServ\\www\\DokuWiki\\lib\\plugins\\snippeter\\action.php on line 24, referer: http://wiki.guden.lan/dokuwiki/doku.php?id=planning:p21:attachimages
> [Wed Jul 18 16:10:09.728254 2018] [:error] [pid 4220:tid 720] [client 192.168.10.138:53926] PHP Warning:  scandir(../../data/pages/snippets): failed to open dir: No such file or directory in D:\\RAGs\\VertrigoServ\\www\\DokuWiki\\lib\\plugins\\snippeter\\action.php on line 24, referer: http://wiki.guden.lan/dokuwiki/doku.php?id=planning:p21:attachimages
> [Wed Jul 18 16:10:09.728254 2018] [:error] [pid 4220:tid 720] [client 192.168.10.138:53926] PHP Warning:  scandir(): (errno 2): No such file or directory in D:\\RAGs\\VertrigoServ\\www\\DokuWiki\\lib\\plugins\\snippeter\\action.php on line 24, referer: http://wiki.guden.lan/dokuwiki/doku.php?id=planning:p21:attachimages
> [Wed Jul 18 16:10:09.728254 2018] [:error] [pid 4220:tid 720] [client 192.168.10.138:53926] PHP Warning:  Invalid argument supplied for foreach() in D:\\RAGs\\VertrigoServ\\www\\DokuWiki\\lib\\plugins\\snippeter\\action.php on line 35, referer: http://wiki.guden.lan/dokuwiki/doku.php?id=planning:p21:attachimages

![2018-07-18_161411](https://user-images.githubusercontent.com/1150990/42905489-3bbec174-8aa6-11e8-8f53-5252412352b6.png)

**Comment by geco2** [comment] 2018-07-18 20:42
Thank you for that extra mile gone to support my trouble shooting efforts! Really appreciated!

Realized that i never ever tested the plugin running on a windows host. That could be missing peace in the puzzle. Let me try to setup an instance accordingly to get a bug fix.

**Comment by geco2** [comment] 2018-07-20 22:36
the new version should work now... While create that little fix i found some other room for improvement ;-)

Please let me know if the actual version works for you.

Regards,

Andi

**Comment by kdmoyers** [comment] 2018-08-15 12:13
Didn't work, toolbar still disappears when plugin is enabled, reappears when disabled.

At this point, I have to suspect there is something bizarre about my config here that is causing it.  I'll keep tinkering as I come up with ideas, and if I discover what it is, I'll report back here.

**Comment by geco2** [comment] 2018-08-17 20:29
sad to here... Let me know if i can support and good luck ;-) !

Regards,

Andi

**Closed by geco2** 2018-08-17 20:29 UTC
